[package]
name = "batman-hash"
version = "0.1.0"
authors = ["Lucas <genevasterm@protonmail.ch>"]
edition = "2018"

[dependencies]
ggez = "0.5.1"
nalgebra = "0.25.3"

gfx_core = "0.9.2"
gfx_device_gl = "0.16.2"

imgui = "0.7.0"
imgui-gfx-renderer = "0.7.0"