name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --release
    - name: Run Tests
      run: cargo test --release
